name: Build and Test WW130_cli

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  ARM_TOOLCHAIN_VERSION: 13.3.rel1
  ARM_TOOLCHAIN_URL: https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache ARM toolchain
        uses: actions/cache@v3
        id: cache-arm-toolchain
        with:
          path: /usr/local/arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi
          key: ${{ runner.os }}-arm-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}

      - name: Set up build dependencies
        if: steps.cache-arm-toolchain.outputs.cache-hit != 'true'
        run: |
          wget -q ${{ env.ARM_TOOLCHAIN_URL }}
          tar -xf arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi.tar.xz
          sudo mv arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi /usr/local/

      - name: Add ARM toolchain to PATH
        run: echo "/usr/local/arm-gnu-toolchain-${{ env.ARM_TOOLCHAIN_VERSION }}-x86_64-arm-none-eabi/bin" >> $GITHUB_PATH

      - name: Update APP_TYPE variable
        run: |
          sed -i 's/APP_TYPE = .*/APP_TYPE = ww130_cli/' EPII_CM55M_APP_S/app/ww_projects/ww.mk

      - name: Build WW130_cli
        run: |
          cd EPII_CM55M_APP_S/
          make clean
          make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WW130_cli-build
          path: EPII_CM55M_APP_S/build/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: WW130_cli-build
          path: EPII_CM55M_APP_S/build/

      - name: Run tests
        run: |
          # Add your test commands here
          # Example:
          # ./EPII_CM55M_APP_S/build/WW130_cli initialize_fatfs
          # ./EPII_CM55M_APP_S/build/WW130_cli initialize_camera
          # ./EPII_CM55M_APP_S/build/WW130_cli example_capture
          echo "Running tests..."
          # Replace this with actual test commands
